new: github workflows deployment.yaml

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -15,6 +15,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+      - name: Verify GH_PAT is present
+        env:
+          PAT: ${{ secrets.GH_PAT }}
+        run: |
+          if [ -z "$PAT" ]; then
+            echo "❌ GH_PAT is missing or empty!"
+            exit 1
+          else
+            echo "✅ GH_PAT is loaded! Length: ${{ secrets.GH_PAT }} characters."
+          fi
+
       # Step 1: Checkout repository code
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -111,6 +123,8 @@ jobs:
           if git diff --staged --quiet; then
             echo "No changes in deployment manifests to commit."
           else
+
+            echo "https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main"
             git commit -m "ci: update image tags to ${{ env.SHORT_SHA }} [skip ci]"
             
             # Authenticate the push with your secret PAT
